services:
  app:
    build: .
    ports:
      - "5173:5173"  # フロントエンド（Vite）
      - "3001:3001"  # バックエンド（Express）
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/client/node_modules
    #   - /app/server/node_modules
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
